version: '3'
services:
  bank:
    build:
      context: ./bank
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - idp

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - idp
      - bank

  idp:
    build:
      context: ./idp
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
